#!/home/akhil/anaconda3/bin/python
print("Content-type: text/html\n")
from addPath import addPath
addPath()
import form
import variables, subprocess, cgi, options
options.nav('docker')
variables.style("../style.css")
variables.style("../form.css")
store=cgi.FieldStorage()
if store.getvalue('name') and store.getvalue('image'):
    name=store.getvalue('name')
    image=store.getvalue('image')
    out=subprocess.getstatusoutput("sudo docker run -dit --name {0} {1}".format(name,image))
    if out[0]==0:
        print("<div class='success'>")
        print("Created container with id : <br>",out[1])
        print("</div>")
    else:
        print("<div class='error'>")
        print(out[1])
        print("</div>")
imagesList=subprocess.getoutput("sudo docker images | awk '{print $1\":\"$2}'").split('\n')
f=form.form()
f.heading="Launch a container"
f.params={'Name':{'type':'text','name':'name'},'Image':{'type':'select','name':'image','values':imagesList}}
f.out()